name = "iframe-playground"
workers_dev = true
compatibility_date = "2022-05-03"

[vars]
ENVIRONMENT = "dev"

[env.dev.vars]
ENVIRONMENT = "dev"

[env.staging.vars]
ENVIRONMENT = "staging"

[env.production.vars]
ENVIRONMENT = "production"
